### ISSUE TITLE
Cannot find executable - Windows 10

### ISSUE THREAD

**Issue by reubster** [sqlfluff/vscode-sqlfluff#36] opened 2021-07-22 09:13 UTC
I'm getting the vscode error message on opening any SQL file; 

"Cannot lint <..file>. The executable was not found. Use the 'Executable Path' setting to configure the location of the executable" 

In the workspace settings.json, there is the configuration; 

"sql.linter.executablePath": "${workspaceFolder}\\.venv\\Scripts\\sqlfluff.exe"

... which exists. 

I've also tried;
-  unix style path, 
- explicit path... 
- with / without .exe extension
- with / without the "sqlfluff" ~ just the directory 

Not sure what else to do. I've read the other similar issues but can't find a solution. 

I have 
> which sqlfluff 
/c/source/analytics-dbt-models/.venv/Scripts/sqlfluff
> sqlfluff --version 
sqlfluff, version 0.5.6

I have sqlfluff extension 0.0.15

**Comment by RobertOstermann** [comment] 2022-08-10 21:22
Please update to v0.0.6 and let me know if the problem is still occurring.

**Comment by tanzaho** [comment] 2022-08-24 16:26
Hi @RobertOstermann ,

I'm posting here since my latest comment was probably made under an irrelevant issue.

--

My colleagues using Windows have troubles to make our sqlfluff setup working even-though they are using v0.0.6.
I see that they are not alone by looking at the current issue, and to some other tickets ([here](https://github.com/sqlfluff/vscode-sqlfluff/issues/23) or [here](https://github.com/sqlfluff/vscode-sqlfluff/issues/4)).

As @reubster we think the issue relates to setting of the executable path. We have tried several paths and here is our latest `settings.json`.

```
{
    "workbench.colorTheme": "Default Dark+",
    "files.associations": {
        "*.sql": "jinja-sql"
    },
    "editor.bracketPairColorization.enabled": true,
    "diffEditor.ignoreTrimWhitespace": false,
    "sql.linter.executablePath": "C:/Anaconda/Scripts/sqlfluff",
    "sqlfluff.executablePath": "C:/Anaconda/Scripts/sqlfluff",
    "sqlfluff.linter.run": "onSave",
    "githubPullRequests.pullBranch": "never",
    "sqlfluff.config": ".sqlfulff",
    "sqlfluff.dialect": "bigquery",
    "sqlfluff.ignoreLocalConfig": true,
    "editor.rulers": [80],
    "sqlfluff.excludeRules": [
    
    ]
}
```

For the path, we tried several variations and got errors in the Dev Console, or as a warning popup in VScode.

- `C:\\Anaconda\\Scripts\\sqlfluff`
-  `C:/Anaconda/Scripts/sqlfluff` 

Resulted in an error in the dev console
```
workbench.desktop.main.js:86 [Extension Host] SyntaxError: Unexpected token E in JSON at position 0
	at JSON.parse (<anonymous>)
	at c:\Users\pguillotte\.vscode\extensions\dorzey.vscode-sqlfluff-0.0.6\out\src\extension.js:3:4751
	at Array.forEach (<anonymous>)
	at L.process (c:\Users\pguillotte\.vscode\extensions\dorzey.vscode-sqlfluff-0.0.6\out\src\extension.js:3:4722)
	at Socket.a (c:\Users\pguillotte\.vscode\extensions\dorzey.vscode-sqlfluff-0.0.6\out\src\extension.js:3:3611)
	at Socket.emit (node:events:402:35)
	at endReadableNT (node:internal/streams/readable:1343:12)
	at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
<img width="908" alt="Capture d’écran 2022-08-24 à 17 05 01" src="https://user-images.githubusercontent.com/2247438/186471988-96cfcf25-779a-4db4-8d3c-1c1d5910a9fe.png">


- /c/Anaconda/Scripts/sqlfluff

Resulted in a warning message in VSCode saying the executable was not found.
> Cannot lint _path/to/file_ . The executable was not found. Use the 'Executable Path' setting to configure the location of the executable.

<img width="610" alt="Capture d’écran 2022-08-24 à 17 18 38" src="https://user-images.githubusercontent.com/2247438/186471890-abfd42fd-d8a8-43cc-9ed0-7514a6d13ecb.png">

**Comment by noel** [comment] 2022-08-24 18:12
Are you sure that the right Python environment is selected in vs Code?

**Comment by tanzaho** [comment] 2022-08-25 08:33
I'm not sure which environment is the good one, but for the previously mentioned case, the interpreter is `C:\Anaconda\python.exe`

![Capture](https://user-images.githubusercontent.com/2247438/186616354-e9036ac3-301f-4324-888f-7d6882daba3d.PNG)

**Comment by RobertOstermann** [comment] 2022-08-26 18:43
I think this is a problem with the extension reading the JSON response from the sqlfluff linter. Can you check the output for the command `sqlfluff lint --format json {other arguments and filename}` when run on the file/files you are having issues with? That should give you a JSON response and you could check if the response is a valid JSON string or not.

**Comment by PaulGuillotte** [comment] 2022-08-30 14:42
Hello @RobertOstermann ! I'm @tanzaho 's colleague having the issue with the SQL Fluff extension on VS Code (Windows).
The JSON I get using your method is the following : 

`[{"filepath": "models\\marts\\core\\fct_ads.sql", "violations": [{"line_no": 6, "line_pos": 82, "code": "L001", "description": "Unnecessary trailing whitespace."}, {"line_no": 6, "line_pos": 83, "code": "L016", "description": "Line is too long."}, {"line_no": 13, "line_pos": 7, "code": "L010", "description": "Keywords must be lower case."}]}]`

which looks like a valid JSON when checked using a validator. Maybe the problem is elsewhere ? The `\\` in the path seems a bit suspicious

**Comment by RobertOstermann** [comment] 2022-08-30 17:20
@PaulGuillotte I have recently released v0.0.7 which replaces the `\\` with `/` and hopefully helps fix your issue. Give that version a try and let me know if it works.

**Comment by RobertOstermann** [comment] 2022-08-30 21:05
So you are still getting this error in the dev console after the update? You should be using one of these two paths.
* `C:\\Anaconda\\Scripts\\sqlfluff`
* `C:/Anaconda/Scripts/sqlfluff`

```
workbench.desktop.main.js:86 [Extension Host] SyntaxError: Unexpected token E in JSON at position 0
	at JSON.parse (<anonymous>)
	at c:\Users\pguillotte\.vscode\extensions\dorzey.vscode-sqlfluff-0.0.6\out\src\extension.js:3:4751
	at Array.forEach (<anonymous>)
	at L.process (c:\Users\pguillotte\.vscode\extensions\dorzey.vscode-sqlfluff-0.0.6\out\src\extension.js:3:4722)
	at Socket.a (c:\Users\pguillotte\.vscode\extensions\dorzey.vscode-sqlfluff-0.0.6\out\src\extension.js:3:3611)
	at Socket.emit (node:events:402:35)
	at endReadableNT (node:internal/streams/readable:1343:12)
	at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by PaulGuillotte** [comment] 2022-08-31 13:15
Yes, I tried with both paths you mentionned and in both cases I've got he same error in the dev console, which is the one you pasted above.

**Comment by RobertOstermann** [comment] 2022-09-01 01:21
Ok, I am out of ideas. If you wanted to pull down this repo and debug the problem yourself you might have some luck. I'll throw on the help wanted tag and maybe someone else will have more knowledge of how to solve this problem.

**Comment by PaulGuillotte** [comment] 2022-09-13 12:09
For your information, it's now working perfectly for me (on my 2 computers) with v0.1.0

**Comment by RobertOstermann** [comment] 2022-09-13 14:08
Closing this issue. For any other problems, please create a new issue.

**Closed by RobertOstermann** 2022-09-13 14:08 UTC
